package:
  name: version_number_extractor
  version: 3.0.0

source:
  fn: version_number_extractor-conda.zip
  url: ../dist/version_number_extractor-conda.zip

build:
  number: 0
  binary_relocation: False
  detect_binary_files_with_prefix: False
  include_recipe: False

about:
  home: http://modloader64.com
  license: GPL-3
  summary: Extract version information from package.json